# Mixed point label font styles

Create [ggplot_mixed_fontstyles.md](ggplot_mixed_fontstyles.md): `R -e 'library(knitr); knit("ggplot_mixed_fontstyles.Rmd")'`

This recipe shows a simple example for having some point labels in bold font in a scatter plot.

Required libraries:
```{r message=FALSE}
library(ggplot2)
library(ggrepel)
```

Create data frame:
```{r}
name <- c("abc","cde","fgh")
x <- c(1.5,2,2.5)
y <- c(1.5,2,2.5)
df <- data.frame(name,x,y)
df
```

Add column for font face using a y-value cutoff:
```{r}
df$fontface <- ifelse(y > 2.0, "bold", "plain")
df$abovethreshold <- ifelse(y > 2.0, TRUE, FALSE)
```

```{r ggplot_mixed_fontstyles}
ggplot(df,aes(x=x, y=y)) +
  geom_point(aes(shape=abovethreshold,size=abovethreshold,color=abovethreshold)) +
  geom_text_repel(aes(label=name,fontface=fontface)) +
  theme_bw() +
  scale_shape_manual(guide=F,values=c(16,42)) +
  scale_size_manual(guide=F,values=c(3,10)) +
  scale_color_discrete(guide=F)+
  xlab("") +
  ylab("") +
  xlim(1,3) +
  ylim(1,3)
```


